# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_title', models.CharField(max_length=250, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200)),
                ('offer_price', models.FloatField(default=0, verbose_name='Цена')),
                ('dimension', models.CharField(blank=True, max_length=50, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Subtags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_url', models.CharField(max_length=250, unique=True)),
                ('tag_title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Дополнительные теги',
                'verbose_name_plural': 'Дополнительные теги',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_url', models.CharField(max_length=250, unique=True)),
                ('tag_title', models.CharField(max_length=250)),
                ('tag_publish', models.BooleanField()),
                ('tag_priority', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Основные теги',
                'verbose_name_plural': 'Основные теги',
            },
        ),
        migrations.AddField(
            model_name='subtags',
            name='tag_parent_tag',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='import.Tags'),
        ),
        migrations.AddField(
            model_name='offers',
            name='offer_sub_tag',
            field=models.ManyToManyField(blank=True, to='import.Subtags', verbose_name='Группа 2 уровня'),
        ),
        migrations.AddField(
            model_name='offers',
            name='offer_tag',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='import.Tags', verbose_name='Группа 1 уровня'),
        ),
        migrations.AlterIndexTogether(
            name='offers',
            index_together=set([('id', 'slug')]),
        ),
    ]
