# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0002_offers_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='offer_text',
            field=models.TextField(default=None, null=True, verbose_name='Полное описание'),
        ),
    ]
